pipeline {
    // هنا بنربط تاسك 3 بتاسك 2 (بنشغل الشغل على الكالي)
    agent {
        label 'linux-agent'
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Pulling code from GitHub...'
                checkout scm
            }
        }
        
        stage('Build Java App') {
            steps {
                // بندخل جوه الفولدر اللي عملناه عشان نلاقي الجرادل
                dir('Task3_Java_Gradle') {
                    echo 'Building Java App with Gradle...'
                    sh 'gradle clean build -x test'
                }
            }
        }
        
        stage('Test App') {
            steps {
                dir('Task3_Java_Gradle') {
                    echo 'Running JUnit Tests...'
                    sh 'gradle test'
                }
            }
        }
        
        stage('Run App') {
            steps {
                dir('Task3_Java_Gradle') {
                    echo 'Executing the Application...'
                    sh 'gradle run'
                }
            }
        }
    }
}
