pipeline {
    agent {
        label 'linux-agent'
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Pulling code from GitHub...'
                checkout scm
            }
        }
        
        stage('Build Java App') {
            steps {
                dir('Task3_Java_Gradle') {
                    echo 'Building Java App with Gradle...'
                    sh 'bash -lc "gradle clean build -x test"'
                }
            }
        }
        
        stage('Test App') {
            steps {
                dir('Task3_Java_Gradle') {
                    echo 'Running JUnit Tests...'
                    sh 'bash -lc "gradle test"'
                }
            }
        }
        
        stage('Run App') {
            steps {
                dir('Task3_Java_Gradle') {
                    echo 'Executing the Application...'
                    sh 'bash -lc "gradle run"'
                }
            }
        }
    }
}
