pipeline {
    agent {
        label 'linux-agent'
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Pulling code from GitHub...'
                checkout scm
            }
        }
        
        // دي المرحلة السحرية اللي هتحل المشكلة من جذورها
        stage('Download Gradle') {
            steps {
                dir('Task3_Java_Gradle') {
                    echo 'Downloading Gradle directly to the workspace...'
                    sh '''
                    wget -q -nc https://services.gradle.org/distributions/gradle-8.5-bin.zip || true
                    unzip -q -o gradle-8.5-bin.zip
                    '''
                }
            }
        }
        
        stage('Build Java App') {
            steps {
                dir('Task3_Java_Gradle') {
                    echo 'Building Java App...'
                    // هنا بنستخدم الأداة اللي لسه محملينها حالا
                    sh './gradle-8.5/bin/gradle clean build -x test'
                }
            }
        }
        
        stage('Test & Run App') {
            steps {
                dir('Task3_Java_Gradle') {
                    echo 'Running Tests and executing...'
                    sh './gradle-8.5/bin/gradle test'
                    sh './gradle-8.5/bin/gradle run'
                }
            }
        }
    }
}
